version: '3.8'

services:
  db:
    container_name: nwbnk_db
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postrgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_pass
      - POSTGRES_DB=nwbnk

  backend:
    container_name: nwbnk_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app/:/app/
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nwbnk.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
