"""First commit

Revision ID: 7d1686e8c8b0
Revises: 
Create Date: 2021-09-20 22:50:53.241810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d1686e8c8b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('logo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['logo_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'PENDING', 'DELETED', 'APPROVED', name='statusenum'), nullable=True),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('in_game_name', sa.String(length=64), nullable=False),
    sa.Column('discord_name', sa.String(length=64), nullable=True),
    sa.Column('discord_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('SETTLER', 'OFFICER', 'CONSUL', 'GOVERNOR', name='rankenum'), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'PENDING', 'DELETED', 'APPROVED', name='statusenum'), nullable=True),
    sa.Column('bank_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('creator_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('approver_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('bank')
    op.drop_table('company')
    op.drop_table('file')
    # ### end Alembic commands ###
